abc: abc.o abcShort.o
	gcc -ansi -Wall -pedantic -g abc.o abcShort.o -o abc
abc.o: abc.c
	gcc -c -ansi -Wall -pedantic abc.c -o abc.o
abcShort.o: abcShort.c
	gcc -c -ansi -Wall -pedantic abcShort.c -o abcShort.o