my_rottate: my_rottate.o bitwise_rotation.o
	gcc -ansi -Wall -pedantic -g my_rottate.o bitwise_rotation.o -o my_rottate
my_rottate.o: my_rottate.c
	gcc -c -ansi -Wall -pedantic my_rottate.c -o my_rottate.o
bitwise_rotation.o: bitwise_rotation.c
	gcc -c -ansi -Wall -pedantic bitwise_rotation.c -o bitwise_rotation.o